# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ac6kPe_0loGJFim7GpKYNtjXijs5WVlz
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([45,23,12,5,15,])
mylabels=["English","Dasturlash","Tarix","Kimyo","Iqtisod"]
plt.pie(x,labels=mylabels)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 2 * np.pi, 500)
y_sin = np.sin(x)
y_cos = np.cos(x)
plt.figure(figsize=(10, 6))
plt.plot(x, y_sin, label='sin(x)', color='blue', linestyle='-', linewidth=2)
plt.plot(x, y_cos, label='cos(x)', color='green', linestyle='--', linewidth=2)
plt.title('Sinus va Kosinus Grafiklari', fontsize=16)
plt.xlabel('X qiymatlari', fontsize=12)
plt.ylabel('Y qiymatlari', fontsize=12)
plt.axhline(0, color='black', linewidth=0.8, linestyle='--')
plt.axvline(0, color='black', linewidth=0.8, linestyle='--')
plt.grid(color='gray', linestyle=':', linewidth=0.5)
plt.legend(fontsize=12)
plt.show()